networks:
  traefik:
    external: true

services:
  traefik:
    image: traefik:3
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "80:80"
      # - "443:443"  # Uncomment for production
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik-local.yaml:/etc/traefik/traefik.yaml:ro
      # - ./config/traefik-prod.yaml:/etc/traefik/traefik.yaml:ro  # Uncomment for production (and comment out local)
      - ./config/conf/:/etc/traefik/conf/:ro
      # - ./letsencrypt:/letsencrypt  # Uncomment for production
      # - ./logs:/var/log/traefik  # Uncomment for production
    # environment:  # Uncomment for production with Cloudflare DNS challenge
    #   - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
