api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
  file:
    directory: /etc/traefik/conf/
    watch: true

log:
  level: "DEBUG"
